---

- hosts: all
  become: true
  tasks:

  - name: Update repository index
    apt:
      update_cache: yes

  - name: Install Semaphore
    community.general.snap:
      name:
        - semaphore

  - name: install mysql-server
    apt:
     name: mysql-server
     state: latest

  - name: Mysql secure installation
    shell:
      Y \
      2 \
      Y \
      Y \
      Y \
      Y


  - name: Stop Semaphore
    shell:
      snap stop semaphore

  - name: Add admin user
    shell:
      semaphore user add --admin \
      --login kobe \
      --name kobe \
      --email=kobe.willaert@student.howest.be \
      --password=Test123

  - name: Start Semaphore
    shell:
      snap start semaphore

